version: '3' # Docker Compose file version.

services:
  nginx:
    container_name: nginx # Container name for the Nginx service.
    image: nginx # Docker image used for Nginx.
    ports:
      - 80:80 # Mapping port 80 inside the container to port 80 on the host.
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf # Mounting a local configuration file into the Nginx container.
      - ./www:/var/www/public_html # Mounting a local directory into /var/www/public_html within the container.
    depends_on:
      - php
      - mysql # Waiting for the PHP and MySQL services to start before launching Nginx.

  php:
    container_name: php # Container name for the PHP service.
    build: ./www # Path to the directory with a Dockerfile for creating the container image.
    volumes:
      - ./www:/var/www/public_html # Mounting a local directory into /var/www/public_html within the container.
    depends_on:
      - mysql # Waiting for the MySQL service to start before launching PHP.

  mysql:
    container_name: mysql # Container name for the MySQL service.
    image: mysql # Docker image used for MySQL.
    volumes:
      - ./mysql-data:/var/lib/mysql # Mounting a local directory for storing MySQL data.
    environment:
      - MYSQL_ROOT_PASSWORD=root # Setting the password for the MySQL root user.

  phpmyadmin:
    container_name: phpmyadmin # Container name for the phpMyAdmin service.
    image: phpmyadmin # Docker image used for phpMyAdmin.
    ports:
      - 1500:80 # Mapping port 1500 inside the container to port 80 on the host.
    environment:
      - PMA_HOST=mysql # Specifying the MySQL host to which phpMyAdmin will connect.
    depends_on:
      - mysql # Waiting for the MySQL service to start before launching phpMyAdmin.
